spring:
  application:
    name: employee-producer

server:
  port: 8084
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    healthcheck:
      enabled: true