spring:
  application:
    name: first-service

server:
  port: 8083
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    healthcheck:
      enabled: true