spring:
  application:
    name: first-service

server:
  port: 17210
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8671/eureka
    healthcheck:
      enabled: true

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"