spring:
  application:
    name: second-service

server:
  port: 8082
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8671/eureka
    healthcheck:
      enabled: true