server:
  port: 8080

spring:
  application:
    name: gateway-service

first:
  service:
    id: employeeModule
    uri: lb://FIRST-SERVICE
    predicates: /employee/**

second:
  service:
    id: consumerModule
    uri: lb://SECOND-SERVICE
    predicates: /consumer/**

employee:
  info:
    service:
      id: employeeConsumer
      uri: lb://EMPLOYEE-CONSUMER
      predicates: /employee-info/**

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    healthcheck:
      enabled: true
